#!/bin/sh
# *********************************************************************
#  Proceso Shell Generica para Desarrollo
#
#  Date        : Abril 2018
#  Filename    : config.sh
#  Description : Shell libreria de variables locales.
#
# *********************************************************************

#Path locales
_PATH=`cd ..; cd ..; pwd`
PATH_APP=$_PATH/app
PATH_DATA=$_PATH/data
#cd ../..
#PATH=`pwd`
#PATH_APP=$PATH/app;
#PATH_DATA=$PATH/data;
PATH_SHL=$PATH_APP/SHL/;							export PATH_SHL;
PATH_CNF=$PATH_APP/CNF/;							export PATH_CNF;
PATH_BTEQ=$PATH_APP/BTEQ/;						export PATH_BTEQ;
PATH_JAR=$PATH_APP/JAR/;							export PATH_JAR;
PATH_SQL=$PATH_APP/SQL/;							export PATH_SQL;
PATH_LOG=$PATH_DATA/LOG/;							export PATH_LOG;
PATH_TMP=$PATH_DATA/TMP/;							export PATH_TMP;
PATH_PY=$PATH_APP/PY/;							export PATH_PY;


#PATH_SHL=/home/malenantillanca_everis/PPV/app/SHL/;							export PATH_SHL;
#PATH_CNF=/home/malenantillanca_everis/PPV/app/CNF/;							export PATH_CNF;
#PATH_BTEQ=/home/malenantillanca_everis/PPV/app/BTEQ/;							export PATH_BTEQ;
#PATH_JAR=/home/malenantillanca_everis/PPV/app/JAR/;							export PATH_JAR;
#PATH_SQL=/home/malenantillanca_everis/PPV/app/SQL/;							export PATH_SQL;
#PATH_LOG=/home/malenantillanca_everis/PPV/data/LOG/;							export PATH_LOG;
#PATH_TMP=/home/malenantillanca_everis/PPV/data/TMP/;							export PATH_TMP;
#PATH_PY=/home/malenantillanca_everis/PPV/app/PY/;							export PATH_PY;

#GCP directories

PRM_GCP_BUCKET=sp-os-rca-bkt-01;							export PRM_RUTA_GCP_BUCKET;
PRM_GCP_PROJECT=sp-os-rca-dev-01;							export PRM_RUTA_GCP_PROJECT;
PRM_GCP_PROJECT_BQ=sp-os-rca-dev-01;						export PRM_GCP_PROJECT_BQ;
PRM_GCP_ESQUEMA_TABLAS=EXODSTB;								export PRM_RUTA_GCP_ESQUEMA_TABLAS;
PRM_GCP_ESQUEMA_MAESTRO=REPADMIN;							export PRM_RUTA_GCP_ESQUEMA_MAESTROS;
PRM_GCP_ESQUEMA_REPORTES=VW_EXODSTB;						export PRM_RUTA_GCP_ESQUEMA_REPORTES;
PRM_GCP_ESQ_PARAMETROS=PRM_EXODSTB;							export PRM_GCP_ESQ_PARAMETROS;
PRM_RUTA_GCP_PPV=pasivos_por_volar;							export PRM_RUTA_GCP_CSV_AUDITORIA;
PRM_RUTA_GCP_CSV_EJECUCIONES=pasivos_por_volar/ejecuciones;	export PRM_RUTA_GCP_CSV_EJECUCIONES;



#BigQuery 
PRM_HCSV_VENTAS=CIA,FORMATO_SERIE,NUMERO_TKT_PADRE,CORRELATIVO_COJ,NUM_CUPON,ESTADO_CONTABLE,GRUPO_CONTABLE,FECHA_CONTABLE_SAP,FECHA_CONTABLE_REVERA,FECHA_VENTA,PAIS_EMISION,CLIENTE,SUCURSAL,TIPO_PRODUCTO,TRNC,RFIC_RFISC,FLIGHT_INDICATOR,TIPO_VTA_ESTANDAR,TIPO_VTA_ESPECIAL,OPERADOR,VUELO,FECHA_VUELO,CUIDAD_ORIGEN,CUIDAD_DESTINO,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,MONEDA,MNT_VTA_USD,MNT_VTA_PAGO,MNT_VTA_FUNC,MNT_COMISIONES_USD,MNT_COMISIONES_PAGO,MNT_COMISIONES_FUNC,MNT_DSC_USD,MNT_DSC_PAGO,MNT_DSC_FUNC,MNT_TAX_YQ_USD,MNT_TAX_YQ_PAGO,MNT_TAX_YQ_FUNC,MNT_TAX_JURO_USD,MNT_TAX_JURO_PAGO,MNT_TAX_JURO_FUNC,MNT_BOARDINGFEE_USD,MNT_BOARDINGFEE_PAGO,MNT_BOARDINGFEE_FUNC ; export PRM_HCSV_VENTAS;
PRM_HCSV_USOS=COMPANIA,FORMATO_SERIE,CUPON,STT_CTBLE_USO,FECHA_CONTABLE,FCH_EMISION,FECHA_USO,GRUPO_CONTABLE,SIST_USO,TRNC_USO,RFIC_RFISC,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,CIUDAD_ORIGEN,CIUDAD_DESTINO,MNT_USO_PAGO,MNT_USO_USD,MNT_USO_FUNC,MNT_COMISIONES_USD,MNT_COMISIONES_PAGO,MNT_COMISIONES_FUNC,MNT_DSC_USD,MNT_DSC_PAGO,MNT_DSC_FUNC,MNT_TAX_YQ_USD,MNT_TAX_YQ_PAGO,MNT_TAX_YQ_FUNC,MNT_TAX_JURO_USD,MNT_TAX_JURO_PAGO,MNT_TAX_JURO_FUNC,MNT_BOARDINGFEE_USD,MNT_BOARDINGFEE_PAGO,MNT_BOARDINGFEE_FUNC; export PRM_HCSV_USOS;
PRM_HCSV_RNU=CIA,DTVT_CDG_CUPON,DCTO,CPN,EVENTO,GRUPO_CONTABLE,EST_CONTABLE,FCH_SAP,FCH_CONTABLE,FCH_EMISION,FCH_REGISTRO,ESPECIE,TRNC,MONEDA,MNT_USD,MNT_PAGO,MNT_LOCAL,OWNER_CONTABLE,FCH_VUELO,FCH_USO,CUIDAD_ORIGEN,CUIDAD_DESTINO,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,BSAR,PAIS,RFIC_RFISC,CARRIER_OPERADOR,CARRIER_MARKETING,NMR_COMPROBANTE,NMR_VUELO,TPO_VTA_ESPECIAL,TPO_VTA_ESTANDAR,MNT_COMISIONES_USD,MNT_COMISIONES_PAGO,MNT_COMISIONES_FUNC,MNT_DSC_USD,MNT_DSC_PAGO,MNT_DSC_FUNC,MNT_TAX_YQ_USD,MNT_TAX_YQ_PAGO,MNT_TAX_YQ_FUNC,MNT_TAX_JURO_USD,MNT_TAX_JURO_PAGO,MNT_TAX_JURO_FUNC,MNT_BOARDINGFEE_USD,MNT_BOARDINGFEE_PAGO,MNT_BOARDINGFEE_FUNC,SIST_USO,GRUPO_CONTABLE_USO,FECHA_CONTABLE_USO; export PRM_HCSV_RNU;
PRM_HCSV_UNR=ID_CUPON,OWNER_CONTABLE,FECHA_EMISION_VTA,ESTATUS_VTA,FECHA_REVERA_VTA,FECHA_SAP_VTA,MNT_USD_VTA,MNT_PAGO_VTA,MNT_FUNC_VTA,COMPANIA,FORMATO_SERIE,CUPON,STT_CTBLE_USO,FECHA_CONTABLE_USO,FECHA_USO,GRUPO_CONTABLE,SIST_USO,TRNC_USO,RFIC_RFISC,CIUDAD_ORIGEN,CIUDAD_DESTINO,AEROPUETO_ORIGEN,AEROPUETO_DESTINO,MNT_USO_PAGO,MNT_USO_USD,MNT_USO_FUN,MNT_COMISIONES_USD,MNT_COMISIONES_PAGO,MNT_COMISIONES_FUNC,MNT_DSC_USD,MNT_DSC_PAGO,MNT_DSC_FUNC,MNT_TAX_YQ_USD,MNT_TAX_YQ_PAGO,MNT_TAX_YQ_FUNC,MNT_TAX_JURO_USD,MNT_TAX_JURO_PAGO,MNT_TAX_JURO_FUNC,MNT_BOARDINGFEE_USD,MNT_BOARDINGFEE_PAGO,MNT_BOARDINGFEE_FUNC; export PRM_HCSV_UNR;

PRM_CIA_VENTAS=CIA;  export PRM_CIA_VENTAS;
PRM_CIA_USOS=COMPANIA;  export PRM_CIA_USOS;
PRM_CIA_RNU=CIA;  export PRM_CIA_RNU;
PRM_CIA_UNR=COMPANIA;  export PRM_CIA_UNR;

PRM_FCH_RNU=FCH_EMISION;  export PRM_FCH_RNU;
PRM_FCH_UNR=FECHA_EMISION_VTA;  export PRM_FCH_UNR;

## Dependencias de python
sudo pip install -r ${PATH_CNF}requirements.txt;